language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-timewarp' ]; then cd .. && eval "mv $currentfolder generator-timewarp" && cd generator-timewarp; fi

